### ISSUE TITLE
Travel safely to Atlanta...

### ISSUE THREAD

**Issue by tommeagher** [ireapps/pycar#10]
Thanks to all of you--@hbillings, @esagara, @chrislkeller, @rdmurphy, @katiepark, @kevinschaul, @richardsalex--for the time, energy and enthusiasm you've put into getting ready for this year's PyCAR.
By my rough count, there have been more than 30 commits to this repo since Jan. 1. I think Thursday's classes are going to be awesome, and it's entirely due to your hard work. So thank you.

Now, get to Atlanta safely and painlessly. For those who are in town, we can huddle up tomorrow evening in the bar to discuss any last-minute details. Otherwise, we'll get rolling Thursday morning, and the first round of drinks Thursday afternoon is on me.

**Comment by rdmurphy** [comment]
:+1: (Made it.)

**Comment by tommeagher** [comment]
PyCARians, sorry we didn't get to meet en masse tonight, but the evening got away from me. Let's plan to meet at 8:40 am at the registration table so we can disperse to our respective classrooms. And @kevinschaul, good luck traveling down here in the morning...
