### ISSUE TITLE
guide project 1 goal to creating a simple report of banks failed in a set of states

### ISSUE THREAD

**Issue by chrislkeller** [ireapps/pycar#12]
- csv.reader()
- csvDictReader()

**Comment by tommeagher** [comment]
We do use these readers in later projects, as it's currently designed.

**Comment by tommeagher** [comment]
@chrislkeller, would you like to revisit this ahead of Jacksonville?

**Comment by chrislkeller** [comment]
@tommeagher: Certainly... Have been buried but I need to get a handle on what's what now in the course materials.

**Comment by tommeagher** [comment]
@chrislkeller 👍

**Comment by tommeagher** [comment]
@chrislkeller Want to take a swing at this for 2018?

**Comment by chrislkeller** [comment]
Four - FOUR! - years later I have no idea what this means...

Digging in.

**Comment by hbillings** [comment]
Good grief I miss being part of this group. Fingers crossed that next year Life sees fit to let me pester you all again. <3

**Comment by rdmurphy** [comment]
I haven't taught PyCAR years but I still enjoy the annual alerts that yank us all back in here

**Comment by tommeagher** [comment]
This is going to be our sixth year, so we have quite a community of alumni now. Glad you enjoy the annual return of the Github discussion, @rdmurphy. 
@hbillings, sorry we won’t see you this year. Hoping you can make it next year.

**Comment by robroc** [comment]
Not sure this is the right issue for this but: I'm seeing a lot of print statements without parens. Are we still teaching Python 2?

**Comment by tommeagher** [comment]
👏 👏 👏  for closing this issue from 2015, @chrislkeller!
