### ISSUE TITLE
Look at adding Ryan Nagle's extra credit code to project 1

### ISSUE THREAD

**Issue by chrislkeller** [ireapps/pycar#19]
Can be found here:
https://github.com/rnagle/pycar/blob/master/project1/extra_credit_state_banks_complete.py

**Comment by tommeagher** [comment]
I added a link to the extra extra credit at the bottom of proposed update to the first project:
https://github.com/ireapps/pycar/blob/denver16/completed/filter_csv_complete.py#L50

Closing this issue for now, but if you want to take another swing at this, Chris, feel free to reopen and push commits.
