### ISSUE TITLE
Balance the breakdown of the teachers...

### ISSUE THREAD

**Issue by chrislkeller** [ireapps/pycar#20]
@hbillings and I talked on Saturday night about a great many things & this came up: we need to involve more women to help teach this class.

I'm sure any of us will step aside if it means increasing the gender ratio.

**Comment by tommeagher** [comment]
Agreed. We were thrilled to have @katiepark join the team this year, but a 2:1 or 3:1 ratio isn't great. I too will gladly step down to make way. Let's keep this issue open and revisit when we start planning in the fall.

**Comment by richardsalex** [comment]
We've gone down to a single, larger PyCAR class this year to make room for more varied, open offerings (and a new R workshop that requires preregistration, led by Ryann Jones and Annie Waldman). As it stands, we're at 1:1 in PyCAR, and while that's an improvement, we always need to try to involve more women. Speaker and teacher diversity is at the forefront of our minds when we plan these conferences, and we are always open to suggestions for new people to tap for these roles.
