### ISSUE TITLE
Is it possible to create a structure to create related lessons without losing the advantages of having many voices involved in the process?

### ISSUE THREAD

**Issue by chrislkeller** [ireapps/pycar#21]
Based on suggestion at [PyCAR 15 feedback thread](https://github.com/ireapps/pycar/issues/17)

@mikejcorey writes:

>Could we organize a (small) committee of Python folks to facilitate this? The group could take suggestions and feedback such as what's happening on this thread, post a recommendation, get some more feedback, and take a yea-nay vote?
>
>I hate committees as much as the next journalist, but Python has made a big impact on the NICAR community, and I don't want to ruin it by big-footing ourselves into the rest of the conference.

@esagara writes:

>Can we standardize curriculum throughout the Python track (standardize may not be the right word)? Can we make it so concepts learnt in an intro course at the beginning of the day/conference are reinforced/expanded upon in more advanced classes further on in the day/conference? It would also help if we split up the main PyCAR course to sessions throughout the week. We could fill in gaps where needed from the more advanced classes.

@chrislkeller writes:

>I think my own stumbling point in thinking through this is mentioned in your last heading: without losing the advantages of having many voices involved in the process. The gorgeous thing about NICAR is someone can obtain knowledge and share it with others in a really direct way. No one wants to lose that. No one wants a curriculum committee to thumbs up or thumbs down sessions.
>
>But I too felt those who want to learn would benefit from core concepts being taught, explained and demonstrated over and over - repetition, practice and muscle memory of you will. Landmarks, touchstones, repeated use of terms, doing and seeing are all valuable when it comes to learning.
>
>And this speaks to the scope of what we did with PyCAR right? Devil's advocate: If there are two sessions in which participants will be scraping websites, did we need to do that during PyCAR?

**Comment by richardsalex** [comment]
We've made an attempt to centralize planning of different coding avenues (Python, R, Ruby, JS) by having a couple of volunteers in each help organize "tracks" that range from novice to more intermediate/advanced. The other goal here by doing this is to help keep lines of communication open between teachers ahead of the conference while everyone plans there classes. We'll see if and how it works and adjust accordingly for 2017.
