### ISSUE TITLE
html file mismatch in project3

### ISSUE THREAD

**Issue by scott2b** [ireapps/pycar#36]
The html file that has been added to project 3 is not the same page that is indicated to be fetched in the README.

**Comment by tommeagher** [comment]
It's good to have a local copy of the file in case the internet sucks. Could've sworn I tested the scraper on that HTML file and it seemed to work. But I could be wrong. Do you want to swap it out for a correct HTML file?

**Comment by scott2b** [comment]
Yes, I think the scraper as written in the completed files matches what you've pushed up as the cached copy in the html directory -- but this doesn't not match what you actually get if you fetch the page. Thus, as written, the scraper does not work for the remote page - so I wasn't sure how best to handle it. I think the class just needs to be removed from the table selection. So, I guess ideally both the scraper and the html file would be replaced to match the specified URL.

**Comment by tommeagher** [comment]
Agree that would be ideal. Do you have the bandwidth to make the changes?Also pinging @esagara in case he has some insight.

**Comment by scott2b** [comment]
done

**Comment by richardsalex** [comment]
Just FYI all, this change won't be reflected on the lab computers tomorrow — we did the final load today for late and updated data. Shouldn't matter because everyone's writing it from scratch.

**Comment by scott2b** [comment]
Ok good to know. Thanks for the heads up
-- 
Scott Bradley
