### ISSUE TITLE
Software requirements

### ISSUE THREAD

**Issue by tommeagher** [ireapps/pycar#41]
We need to give IRE a list this week of software we want pre-loaded on the machines for us. The good news is we'll be on Macs this year.

So I'm pretty sure we'll want: 
* Python 3
* pip
* virtualenv
* virtualenvwrapper
* requests
* bs4
* jupyter 

Anything else I'm not thinking of?

**Comment by zufanka** [comment]
@tommeagher Agate

**Comment by tommeagher** [comment]
@zufanka We've used Anaconda in years past, and from my vague recollection, it seemed to cause as much confusion as it solved. I don't know if I'd recommend students use anaconda at home, but it may not matter much for the purposes of the workshop. I'm agnostic. Whatever's easiest for all involved.

**Comment by tommeagher** [comment]
I gave all of these to our friends at IRE today. If we need to add anything else, let me know. We should be able to `pip install` additional libraries as needed.
