### ISSUE TITLE
Add instructions for getting Jupyter running

### ISSUE THREAD

**Issue by hbillings** [ireapps/pycar#47]
I don't think we ever really told people how to run the exercises at home (I've been trying to get it to run locally and not having a ton of luck, though I think it's because my personal virtualenv setup is foobarred at the moment). That would probably be helpful info!

**Comment by zufanka** [comment]
Install anaconda?

**Comment by chrislkeller** [comment]
@hbillings: You're referring to `pip install`-ing requirements, firing up the notebook, etc...

**Comment by tommeagher** [comment]
We could flesh out this section a bit with more info on jupyter: https://github.com/ireapps/pycar/tree/master/takehome#get-your-machine-ready

**Comment by tommeagher** [comment]
I believe @thejqs has a plan to add something to the repo for this after the conference this year.
