### ISSUE TITLE
Rework basics exercise

### ISSUE THREAD

**Issue by hbillings** [ireapps/pycar#49]
The solitaire example we used to introduce the class seemed to work pretty well as an intro to thinking about programming. I think it would be a good idea to rework the basics exercise to include/build on the solitaire example, so that people can have some context for what the different data types can represent. I've got some notes for running through that card game example, so I can try combining them with the info in the basics notebook if folks give me the thumbs-up!

**Comment by tommeagher** [comment]
👍🏼

**Comment by chrislkeller** [comment]
I loved your use of solitaire to explain programming logic. It extended so nicely throughout the session. Go for it!

**Comment by tommeagher** [comment]
@hbillings, PyCAR2018 is on the horizon. Would you be willing to take this ticket on over the next couple months?

**Comment by hbillings** [comment]
@tommeagher yassssss

**Comment by tommeagher** [comment]
@hbillings awesome. Thank you!!
