### ISSUE TITLE
Add newline='' argument to open?

### ISSUE THREAD

**Issue by robroc** [ireapps/pycar#59]
When using Python 3 in Windows with csv, sometimes an extra carriage return is added after each row. Result: a blank row after each row of data.

I propose adding the `newline = ''` argument to open, as such:

```
with open(FILENAME, 'w', newline='') as outfile:
    writer = csv.writer(outfile)
```

[SO question that addresses this.](https://stackoverflow.com/questions/3348460/csv-file-written-with-python-has-blank-lines-between-each-row/3348664)

**Comment by tommeagher** [comment]
Works for me.

**Comment by tommeagher** [comment]
Hey @robroc, you fixed this in the scraper notebook. Do we need to adjust this in any of the other exercises, do you think?
