### ISSUE TITLE
Who's on first?

### ISSUE THREAD

**Issue by tommeagher** [ireapps/pycar#7]
@Eklucas and our friends at IRE need to know which room each of us will be in this year. 

What do you think about this lineup, to start the discussion?

##Room 0
* @chrislkeller
* @katiepark
* @Kevinschaul
* @Rdmurphy

##Room 1
* @Esagara
* @Hbillings
* @Tommeagher

This is not the order of teaching for the day, just to get us each in a room. If you want to switch rooms, that's no problem, just let me know, on here or on email. 

If I don't hear from any of you in the next 36 hours, I'll assume we're good, and ship this list to Liz. 

On a related note, we could probably use some extra coaches to walk the room and help folks who get stuck. We'll particularly need help in Room 1, and when some of us have to step out to speak at other sessions. 
Who do you think we should recruit to lend a hand?

Thanks,
Tom

**Comment by aboutaaron** [comment]
Yo! just a heads up that @rnagle, @malev are also teaching intro to Python at NICAR this year. Is this related to what you have here @tommeagher?

**Comment by tommeagher** [comment]
@aboutaaron, I hadn't heard that, but I know there a ton of python sessions this year. This one is for the full-day mini boot camp on Thursday. I'm guessing they're doing one of the sessions on another day. If @rnagle and @malev want to help, we'd be happy to have them and to return the favor during their class.

**Comment by eklucas** [comment]
Ok, for the program we're going to go with @tommeagher's suggestions above for room breakdown. But if last-minute switches need to happen, that's not a big deal either.

**Comment by tommeagher** [comment]
Thanks, Liz!
