### ISSUE TITLE
The batting order

### ISSUE THREAD

**Issue by tommeagher** [ireapps/pycar#9]
How do we want to do this next week? Here's a proposed lineup, but please make suggestions if you have other ways you want to do it.

Room 1
Intro - Tom
Project 1 - Tom/Heather
Project 2 - @hbillings 
Lunch
Debugging chat - Heather
Project 3 - @esagara 
Project 4 - Eric/Tom

Coach - @richardsalex 

Room 2
Intro - @chrislkeller
Project 1 - @chrislkeller
Project 2 - @rdmurphy 
Lunch
Debugging chat - ?
Project 3 - @katiepark 
Project 4 - @kevinschaul 

I'm not sure when everybody gets in, but maybe we can meet up Wednesday evening for a drink just to make sure we've dotted all our i's. 

What do you think?

**Comment by kevinschaul** [comment]
I'm flying in early Thursday morning so I'd miss the meetup, but this schedule works for me.

**Comment by chrislkeller** [comment]
@tommeagher - what do you envision the intro being? What highlights should it hit?

I'm good with the lineup, and given some guidance I might be able to pull off the intro... 

I arrive Tuesday afternoon and am up to meet whenever...

**Comment by katiepark** [comment]
Do you have a rough idea of the timing for each project? I have a panel
from 3:20-4:20, but I'm not sure if that'll conflict or not.

**Comment by tommeagher** [comment]
@chrislkeller, the intro is roughly this: https://github.com/ireapps/pycar/blob/master/README.md#introduction
The slides on HaikuDeck are 404'ing for some reason. I'll send a support request to them if they don't show up later tonight (they're in my account index).

@katiepark, it depends on the class. I seem to recall that in our room last year, we basically did project 1 before lunch and then flew through the last two projects quickly as people got more comfortable. Maybe just to be safe, you'd want to do project 2 instead, but either way, you'll probably be fine.

**Comment by hbillings** [comment]
Heeeey, I totally forgot about the debugging session. I am actually pretty terrible at debugging Python (the entirety of my knowledge is occasional use of ipdb). Would anyone else have some bandwidth to either help or take that session over?

**Comment by tommeagher** [comment]
@hbillings, I totally understand. I think we're all starting to feel our bandwidth evaporating. I don't feel particularly well suited for that discussion ("uh, have you tried StackOverflow and PythonJournos?"). Any chance @rdmurphy would want to pick up that debugging talk?

**Comment by tommeagher** [comment]
@chrislkeller, the Haiku Deck slides have been fixed and the link on the main README works: https://www.haikudeck.com/pycar-science-and-technology-presentation-Hrdor9dY3R

**Comment by chrislkeller** [comment]
@tommeagher ... I'll take intro hosting duties... 

Any issues if I take 30 minutes between 4 and 4:30 to meet with Zillow folks about their PR approach to data...?

**Comment by tommeagher** [comment]
@chrislkeller Sounds good to me if it works for the co-teachers in your room. That should be Kevin/Katie at that hour.

And to get back to the question earlier about a debugging session, at this point I'd say we should consider that a WONTFIX and just adlib. With the collective folks in each room, we could do this as an informal discussion rather than a "presentation."
